{
 "title": "django-api",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "视频源个数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(video_insight_stream_source)"
    }
   ]
  },
  {
   "title": "视频流个数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(video_insight_streams{})" }
   ]
  },
  {
   "title": "启动时间",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds*1000)"
    }
   ]
  },
  {
   "title": "虚拟内存大小",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes)",
     "legendFormat": "{{implementation}} {{version}}"
    }
   ]
  },
  {
   "title": "驻留内存",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes)",
     "legendFormat": "{{implementation}} {{version}}"
    }
   ]
  },
  {
   "title": "Python运行版本",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "count(python_info) by(version)", "legendFormat": "Python {{version}}" }
   ]
  },
  {
   "title": "服务状态",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(video_insight_service_pods{state=\"Running\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(video_insight_service_pods{state=\"Pending\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(video_insight_service_pods{state=\"Failed\"}) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "count(video_insight_service_pods{state=\"Unknown\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_virtual_memory_bytes)",
     "legendFormat": "虚拟内存"
    },
    {
     "expr": "avg(process_resident_memory_bytes)",
     "legendFormat": "驻留内存"
    }
   ]
  },
  {
   "title": "返回状态统计",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(django_http_responses_total_by_status[30s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "根据view和方法的请求次数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(django_http_requests_total_by_view_transport_method{view!=\"prometheus-django-metrics\", view!=\"metrics\", view!=\"service-operate\"}[30s])) by (method, view)",
     "legendFormat": "{{view}} {{method}}"
    }
   ]
  },
  {
   "title": "请求处理时间",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(django_http_requests_latency_seconds_by_view_method_bucket{view!=\"metrics\", view!=\"prometheus-django-metrics\"}) by (view,method)",
     "legendFormat": "{{view}} {{method}}"
    }
   ]
  },
  {
   "title": "请求次数by方法",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(increase(django_http_requests_total_by_method[30s])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}